import { useWorkspace } from "@/contexts/WorkspaceContext";
import { trpc } from "@/lib/trpc";
import { Bot, Pause, Play, Plus, Send, X } from "lucide-react";
import { FormEvent, useState } from "react";
import AgentWorkspaceNav, { getAgentWorkspaceCopy } from "../components/app/AgentWorkspaceNav";

export default function Agents() {
  const { workspaceId, workspace } = useWorkspace();
  const [filter, setFilter] = useState<"all" | "active" | "idle" | "paused">("all");
  const [creating, setCreating] = useState(false);
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [workspaceTab, setWorkspaceTab] = useState("overview");
  const agents = trpc.agents.list.useQuery({ workspaceId: workspaceId ?? 0, status: filter === "all" ? undefined : filter }, { enabled: Boolean(workspaceId) });
  const create = trpc.agents.create.useMutation({ onSuccess: () => { agents.refetch(); setCreating(false); } });
  const setStatus = trpc.agents.setStatus.useMutation({ onSuccess: () => agents.refetch() });
  const selected = agents.data?.find(agent => agent.id === selectedId) ?? null;
  const run = trpc.agents.runNow.useMutation();
  const [instruction, setInstruction] = useState("");
  const [runResult, setRunResult] = useState<string | null>(null);
  const deploy = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!workspaceId) return; const form = new FormData(event.currentTarget); create.mutate({ workspaceId, name: String(form.get("name")), purpose: String(form.get("purpose")), description: String(form.get("description") || ""), capabilities: [] }); };
  return <div className="grid gap-4 lg:grid-cols-[1fr_17rem] animate-in fade-in duration-300">
    <div className="col-span-full flex flex-wrap items-center justify-between gap-4 border-b border-[#E8E6E2] pb-4"><div><p className="sn-label text-[#6B7FBF]">{workspace?.workspace.name || "Workspace"} / Agent workspace</p><p className="mt-1 text-sm text-[#6B6660]">Configure context, validate behavior, deploy deliberately, and improve from evidence.</p></div><div className="flex flex-wrap items-center gap-2 text-[10px] uppercase tracking-[.12em] text-[#8C887F]"><span className="rounded-full bg-[#F0EFF8] px-3 py-1.5 text-[#5B6FA8]">01 Build</span><span>→</span><span>02 Test</span><span>→</span><span>03 Deploy</span><span>→</span><span>04 Optimize</span></div></div>
    <section><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><p className="sn-label mb-1">AI Agents</p><h1 className="text-xl font-medium" style={{ fontFamily: "'Instrument Serif', serif", color: "#1A1F3C" }}>{agents.data?.filter(agent => agent.status === "active").length ?? 0} agents active</h1></div><button onClick={() => setCreating(true)} className="inline-flex items-center gap-2 rounded-xl bg-[#1A1F3C] px-4 py-2 text-sm font-medium text-[#F8F6F2] hover:bg-[#252B4A]"><Plus size={16} />Deploy Agent</button></div><div className="mb-4 inline-flex rounded-xl bg-[#E8E6E2] p-1">{(["all", "active", "idle", "paused"] as const).map(value => <button key={value} onClick={() => setFilter(value)} className={`rounded-lg px-3 py-1.5 text-xs font-medium capitalize ${filter === value ? "bg-[#FAFAF8] text-[#1A1F3C] shadow-sm" : "text-[#8C887F]"}`}>{value}</button>)}</div>
      <div className="space-y-3">{agents.isLoading ? <p className="text-sm text-[#8C887F]">Loading agents…</p> : agents.data?.length ? agents.data.map(agent => <article key={agent.id} onClick={() => setSelectedId(selectedId === agent.id ? null : agent.id)} className={`cursor-pointer rounded-2xl border p-5 transition hover:-translate-y-0.5 hover:shadow-lg hover:shadow-[#1A1F3C]/5 ${selectedId === agent.id ? "border-[#D8D6ED] bg-[#F0EFF8]" : "border-[#E8E6E2] bg-[#FAFAF8]"}`}><div className="flex gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#1A1F3C] text-sm font-semibold text-[#F8F6F2]">{agent.name[0]}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-sm font-medium">{agent.name}</h2><Status value={agent.status} /></div><p className="mt-1 truncate text-xs text-[#8C887F]">{agent.purpose}</p></div><div className="flex gap-1">{agent.status === "active" ? <button onClick={event => { event.stopPropagation(); workspaceId && setStatus.mutate({ workspaceId, agentId: agent.id, status: "paused" }); }} aria-label="Pause agent" className="rounded-lg bg-[#F4F3F0] p-2 text-[#6B6660]"><Pause size={14} /></button> : <button onClick={event => { event.stopPropagation(); workspaceId && setStatus.mutate({ workspaceId, agentId: agent.id, status: "active" }); }} aria-label="Activate agent" className="rounded-lg bg-[#F4F3F0] p-2 text-[#6B6660]"><Play size={14} /></button>}</div></div></article>) : <EmptyAgents onCreate={() => setCreating(true)} />}</div>
    </section>
    <aside className="rounded-2xl border border-[#E8E6E2] bg-[#FAFAF8] p-5">{selected ? <><div className="mb-5 border-b border-[#E8E6E2] pb-5"><AgentWorkspaceNav activeId={workspaceTab} onSelect={setWorkspaceTab} /></div><div className="flex items-start justify-between"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#1A1F3C] text-sm font-semibold text-[#F8F6F2]">{selected.name[0]}</div><Status value={selected.status} /></div><h2 className="mt-4 text-base font-medium">{selected.name}</h2><p className="mt-2 text-sm leading-relaxed text-[#6B6660]">{selected.purpose}</p><div className="mt-5 border-t border-dashed border-[#D9D5CE] pt-4"><p className="sn-label text-[#6B7FBF]">{getAgentWorkspaceCopy(workspaceTab, selected.name).eyebrow}</p><p className="mt-2 text-sm font-medium text-[#1A1F3C]">{getAgentWorkspaceCopy(workspaceTab, selected.name).title}</p><p className="mt-1 text-xs leading-relaxed text-[#8C887F]">{getAgentWorkspaceCopy(workspaceTab, selected.name).description}</p></div><form onSubmit={event => { event.preventDefault(); if (!workspaceId || !instruction.trim()) return; setRunResult(null); run.mutate({ workspaceId, agentId: selected.id, instruction }, { onSuccess: result => { setInstruction(""); setRunResult(result.content); } }); }} className="mt-6"><label className="sn-label mb-2 block">Run instruction</label><textarea value={instruction} onChange={event => setInstruction(event.target.value)} className="min-h-24 w-full rounded-xl bg-[#F4F3F0] p-3 text-sm outline-none ring-1 ring-transparent focus:ring-[#6B7FBF]" placeholder="Give this agent a precise task…" /><button disabled={!instruction.trim() || run.isPending} className="mt-2 flex w-full items-center justify-center gap-2 rounded-xl bg-[#1A1F3C] px-3 py-2.5 text-sm font-medium text-[#F8F6F2] disabled:bg-[#D4D1CB]"><Send size={14} />{run.isPending ? "Running…" : "Run now"}</button>{run.error && <p className="mt-2 text-xs text-[#B8675A]">{run.error.message}</p>}</form>{runResult && <article className="mt-4 rounded-xl bg-[#EEF6F6] p-3"><p className="sn-label text-[#4A8B8C]">Run completed</p><p className="mt-2 whitespace-pre-wrap text-sm leading-relaxed text-[#1A1F3C]">{runResult}</p></article>}</> : <div className="grid h-full min-h-56 place-items-center text-center"><div><Bot className="mx-auto mb-3 text-[#B8B4AC]" size={24} /><p className="text-sm font-medium">Select an agent</p><p className="mt-1 text-xs leading-relaxed text-[#8C887F]">View details and run an authorized agent task.</p></div></div>}</aside>
    {creating && <div className="fixed inset-0 z-50 grid place-items-center bg-[#1A1F3C]/35 p-4"><form onSubmit={deploy} className="w-full max-w-md rounded-2xl bg-[#FAFAF8] p-6 shadow-xl"><div className="flex items-center justify-between"><div><p className="sn-label">AI Agents</p><h2 className="mt-1 text-lg font-medium">Deploy an agent</h2></div><button type="button" onClick={() => setCreating(false)} className="rounded-lg p-2 text-[#8C887F]"><X size={18} /></button></div><label className="sn-label mt-5 block">Name<input required name="name" className="mt-2 w-full rounded-xl bg-[#F4F3F0] px-3 py-2.5 text-sm font-normal outline-none ring-1 ring-transparent focus:ring-[#6B7FBF]" /></label><label className="sn-label mt-4 block">Purpose<textarea required name="purpose" className="mt-2 min-h-24 w-full rounded-xl bg-[#F4F3F0] p-3 text-sm font-normal outline-none ring-1 ring-transparent focus:ring-[#6B7FBF]" /></label><label className="sn-label mt-4 block">Description <span className="normal-case text-[#B8B4AC]">optional</span><input name="description" className="mt-2 w-full rounded-xl bg-[#F4F3F0] px-3 py-2.5 text-sm font-normal outline-none ring-1 ring-transparent focus:ring-[#6B7FBF]" /></label><button disabled={create.isPending} className="mt-5 w-full rounded-xl bg-[#1A1F3C] py-2.5 text-sm font-medium text-[#F8F6F2]">{create.isPending ? "Deploying…" : "Deploy agent"}</button>{create.error && <p className="mt-2 text-xs text-[#B8675A]">{create.error.message}</p>}</form></div>}
  </div>;
}
function Status({ value }: { value: "active" | "idle" | "paused" | "error" }) { const colors = { active: "bg-[#EEF6F6] text-[#4A8B8C]", idle: "bg-[#F4F3F0] text-[#8C887F]", paused: "bg-[#FDF4EE] text-[#C5974A]", error: "bg-[#FDF0EE] text-[#B8675A]" }; return <span className={`rounded-full px-2 py-0.5 text-[11px] font-medium capitalize ${colors[value]}`}>{value}</span>; }
function EmptyAgents({ onCreate }: { onCreate: () => void }) { return <div className="rounded-2xl border border-dashed border-[#D4D1CB] bg-[#FAFAF8] py-16 text-center"><Bot className="mx-auto mb-3 text-[#B8B4AC]" /><p className="text-sm font-medium">No agents deployed</p><p className="mt-1 text-xs text-[#8C887F]">Deploy a scoped agent to execute real workspace tasks.</p><button onClick={onCreate} className="mt-4 text-xs font-medium text-[#6B7FBF]">Deploy agent →</button></div>; }
