import { useWorkspace } from "@/contexts/WorkspaceContext";
import { trpc } from "@/lib/trpc";
import { Database, FileText, HardDriveUpload, Plus, RefreshCw, Trash2 } from "lucide-react";
import { ChangeEvent, FormEvent, useState } from "react";

function parseHeaders(value: string) {
  if (!value.trim()) return {};
  const parsed = JSON.parse(value) as unknown;
  if (!parsed || Array.isArray(parsed) || typeof parsed !== "object") throw new Error("Headers must be a JSON object.");
  return Object.fromEntries(Object.entries(parsed).map(([key, headerValue]) => [key, String(headerValue)]));
}

export default function Data() {
  const { workspaceId } = useWorkspace();
  const [tab, setTab] = useState<"sources" | "documents" | "memory">("sources");
  const [connectOpen, setConnectOpen] = useState(false);
  const [formError, setFormError] = useState<string | null>(null);
  const sources = trpc.dataSources.list.useQuery({ workspaceId: workspaceId ?? 0 }, { enabled: Boolean(workspaceId) });
  const documents = trpc.documents.list.useQuery({ workspaceId: workspaceId ?? 0 }, { enabled: Boolean(workspaceId) });
  const memory = trpc.memory.summary.useQuery({ workspaceId: workspaceId ?? 0 }, { enabled: Boolean(workspaceId) });
  const refreshSources = () => void sources.refetch();
  const createSource = trpc.dataSources.create.useMutation();
  const configureSource = trpc.dataSources.configureHttp.useMutation();
  const syncSource = trpc.dataSources.sync.useMutation({ onSuccess: refreshSources });
  const disconnect = trpc.dataSources.disconnect.useMutation({ onSuccess: refreshSources });
  const removeSource = trpc.dataSources.delete.useMutation({ onSuccess: refreshSources });
  const upload = trpc.documents.upload.useMutation({ onSuccess: () => documents.refetch() });
  const removeDocument = trpc.documents.delete.useMutation({ onSuccess: () => documents.refetch() });

  async function uploadFile(event: ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0]; if (!file || !workspaceId) return;
    const encoded = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(",")[1] ?? ""); reader.onerror = reject; reader.readAsDataURL(file); });
    upload.mutate({ workspaceId, originalName: file.name, mimeType: file.type, dataBase64: encoded }); event.target.value = "";
  }

  async function registerSource(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!workspaceId) return; setFormError(null);
    const form = new FormData(event.currentTarget);
    try {
      const headers = parseHeaders(String(form.get("headers") ?? ""));
      const created = await createSource.mutateAsync({ workspaceId, name: String(form.get("name") ?? ""), type: "HTTP API" });
      await configureSource.mutateAsync({ workspaceId, dataSourceId: created.id, connection: { endpoint: String(form.get("endpoint") ?? ""), headers } });
      setConnectOpen(false); refreshSources();
    } catch (error) { setFormError(error instanceof Error ? error.message : "The data source could not be configured."); }
  }

  return <div className="animate-in fade-in duration-300"><div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><p className="sn-label mb-1">Data Management</p><h1 className="text-xl font-medium">Enterprise Data</h1></div><button onClick={() => setConnectOpen(true)} className="inline-flex items-center gap-2 rounded-xl bg-[#1A1F3C] px-4 py-2 text-sm font-medium text-[#F8F6F2]"><Plus size={16} />Connect HTTP Source</button></div><div className="mb-5 grid grid-cols-3 gap-3">{[{ label: "Total Sources", value: sources.data?.length ?? "—" }, { label: "Documents Ready", value: documents.data?.filter(item => item.status === "ready").length ?? "—" }, { label: "Data Health", value: sources.data?.length ? `${Math.round((sources.data.filter(item => item.status === "connected").length / sources.data.length) * 100)}%` : "—" }].map(card => <div key={card.label} className="rounded-2xl border border-[#E8E6E2] bg-[#FAFAF8] p-4"><p className="sn-label">{card.label}</p><p className="mt-2 text-xl font-medium">{card.value}</p></div>)}</div><div className="mb-4 inline-flex rounded-xl bg-[#E8E6E2] p-1">{(["sources", "documents", "memory"] as const).map(value => <button key={value} onClick={() => setTab(value)} className={`rounded-lg px-4 py-1.5 text-xs font-medium capitalize ${tab === value ? "bg-[#FAFAF8] shadow-sm" : "text-[#8C887F]"}`}>{value === "memory" ? "Enterprise Memory" : value}</button>)}</div>
    {tab === "sources" && <section className="overflow-hidden rounded-2xl border border-[#E8E6E2] bg-[#FAFAF8]"><table className="w-full text-left"><thead className="border-b border-[#E8E6E2]"><tr>{["Source", "Type", "Records", "Last Sync", "Status", ""].map(label => <th key={label} className="px-4 py-3 sn-label">{label}</th>)}</tr></thead><tbody>{sources.data?.length ? sources.data.map(source => <tr key={source.id} className="border-b border-[#F4F3F0] last:border-0"><td className="px-4 py-4 text-sm font-medium">{source.name}{!source.configured && <span className="ml-2 text-xs text-[#B8675A]">Needs setup</span>}</td><td className="px-4 py-4 text-sm text-[#8C887F]">{source.type}</td><td className="px-4 py-4 text-sm">{source.recordCount.toLocaleString()}</td><td className="px-4 py-4 text-sm text-[#8C887F]">{source.lastSyncAt ? new Date(source.lastSyncAt).toLocaleString() : "Never"}</td><td className="px-4 py-4"><span className="rounded-full bg-[#F4F3F0] px-2 py-1 text-xs capitalize text-[#6B6660]">{source.status}</span></td><td className="flex gap-2 px-4 py-4"><button disabled={!workspaceId || !source.configured || syncSource.isPending} onClick={() => workspaceId && syncSource.mutate({ workspaceId, dataSourceId: source.id })} className="inline-flex items-center gap-1 text-xs text-[#6B7FBF] disabled:text-[#D4D1CB]"><RefreshCw size={13} />Sync</button><button onClick={() => workspaceId && disconnect.mutate({ workspaceId, dataSourceId: source.id })} className="text-xs text-[#B8675A]">Disconnect</button><button onClick={() => workspaceId && removeSource.mutate({ workspaceId, dataSourceId: source.id })} className="text-xs text-[#B8675A]">Delete</button></td></tr>) : <tr><td colSpan={6} className="px-4 py-14 text-center text-sm text-[#8C887F]">No data sources are connected to this workspace.</td></tr>}</tbody></table>{(syncSource.error || disconnect.error || removeSource.error) && <p className="px-4 pb-4 text-sm text-[#B8675A]">{(syncSource.error || disconnect.error || removeSource.error)?.message}</p>}</section>}
    {tab === "documents" && <section className="space-y-4"><label className="grid cursor-pointer place-items-center rounded-2xl border-2 border-dashed border-[#D4D1CB] bg-[#FAFAF8] px-6 py-12 text-center transition hover:border-[#6B7FBF] hover:bg-[#F0EFF8]"><HardDriveUpload size={25} className="mb-3 text-[#6B7FBF]" /><p className="text-sm font-medium">Upload to Enterprise Memory</p><p className="mt-1 text-xs text-[#8C887F]">PDF, DOCX, XLSX or CSV — up to 10 MB</p><input className="sr-only" type="file" accept=".pdf,.docx,.xlsx,.csv,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,text/csv" onChange={uploadFile} /></label>{upload.error && <p className="text-sm text-[#B8675A]">{upload.error.message}</p>}<div className="overflow-hidden rounded-2xl border border-[#E8E6E2] bg-[#FAFAF8]">{documents.data?.length ? documents.data.map(document => <div key={document.id} className="flex items-center gap-3 border-b border-[#F4F3F0] p-4 last:border-0"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#F4F3F0] text-[#8C887F]"><FileText size={17} /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{document.originalName}</p><p className="mt-1 text-xs text-[#8C887F]">{(document.sizeBytes / 1024).toFixed(1)} KB · {document.status}</p></div><button onClick={() => workspaceId && removeDocument.mutate({ workspaceId, documentId: document.id })} className="rounded-lg p-2 text-[#B8675A]" aria-label="Delete document"><Trash2 size={15} /></button></div>) : <p className="p-12 text-center text-sm text-[#8C887F]">No documents have been uploaded.</p>}</div></section>}
    {tab === "memory" && <section className="rounded-2xl border border-[#E8E6E2] bg-[#FAFAF8] p-8 text-center"><Database size={28} className="mx-auto mb-4 text-[#6B7FBF]" /><h2 className="text-lg font-medium">Enterprise Memory</h2><p className="mx-auto mt-2 max-w-lg text-sm leading-relaxed text-[#8C887F]">The current workspace has {memory.data?.documents ?? 0} ready documents and {memory.data?.dataSources ?? 0} configured data sources. Semantic indexing remains unavailable until an extraction and vector pipeline is configured.</p><div className="mx-auto mt-6 grid max-w-sm grid-cols-3 gap-3">{[{ label: "Documents", value: memory.data?.documents ?? 0 }, { label: "Sources", value: memory.data?.dataSources ?? 0 }, { label: "Chunks", value: memory.data?.indexedChunks ?? 0 }].map(item => <div key={item.label} className="rounded-xl bg-[#F4F3F0] p-3"><p className="text-lg font-medium">{item.value}</p><p className="sn-label mt-1">{item.label}</p></div>)}</div></section>}
    {connectOpen && <div className="fixed inset-0 z-50 grid place-items-center bg-[#1A1F3C]/35 p-4"><form onSubmit={registerSource} className="w-full max-w-md rounded-2xl bg-[#FAFAF8] p-6 shadow-xl"><p className="sn-label">Secure HTTP data source</p><h2 className="mt-1 text-lg font-medium">Configure a connection</h2><p className="mt-2 text-sm text-[#8C887F]">Credentials are encrypted before persistence. The endpoint must be public HTTPS; private and local addresses are rejected.</p><label className="sn-label mt-5 block">Name<input required name="name" className="mt-2 w-full rounded-xl bg-[#F4F3F0] px-3 py-2.5 text-sm font-normal outline-none" /></label><label className="sn-label mt-4 block">HTTPS endpoint<input required name="endpoint" type="url" placeholder="https://api.example.com/v1/records" className="mt-2 w-full rounded-xl bg-[#F4F3F0] px-3 py-2.5 text-sm font-normal outline-none" /></label><label className="sn-label mt-4 block">Headers JSON <span className="normal-case text-[#8C887F]">(optional)</span><textarea name="headers" rows={3} placeholder='{"Authorization":"Bearer …"}' className="mt-2 w-full rounded-xl bg-[#F4F3F0] px-3 py-2.5 font-mono text-xs font-normal outline-none" /></label>{formError && <p className="mt-3 text-sm text-[#B8675A]">{formError}</p>}<div className="mt-5 flex gap-2"><button type="button" onClick={() => setConnectOpen(false)} className="flex-1 rounded-xl border border-[#E8E6E2] py-2.5 text-sm">Cancel</button><button disabled={createSource.isPending || configureSource.isPending} className="flex-1 rounded-xl bg-[#1A1F3C] py-2.5 text-sm font-medium text-[#F8F6F2]">Save connection</button></div></form></div>}
  </div>;
}
