import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { ArrowRight, BrainCircuit, ShieldCheck, Sparkles } from "lucide-react";
import { FormEvent, useState } from "react";
import { Link, useLocation } from "wouter";

const sectionCopy: Record<string, { eyebrow: string; title: string; body: string }> = {
  Platform: { eyebrow: "Platform", title: "The operating layer for enterprise intelligence.", body: "SOPRANOVA connects governed data, agents, workflows, analytics and explainable intelligence inside one workspace." },
  Intelligence: { eyebrow: "Intelligence", title: "Contextual questions, auditable answers.", body: "Ask questions in a persistent workspace conversation. Responses preserve their source inventory and never use a browser-side mock response." },
  "AI Agents": { eyebrow: "AI Agents", title: "Operational agents with visible run history.", body: "Configure workspace agents, execute scoped tasks and retain audited runs with clear status transitions." },
  Solutions: { eyebrow: "Solutions", title: "Clarity for the teams that run the enterprise.", body: "Give leaders and operators a trusted decision surface rather than a fragmented collection of dashboards." },
  Enterprise: { eyebrow: "Enterprise", title: "Tenant isolation is a product feature.", body: "Every operational read and mutation is constrained by workspace membership and role checks on the server." },
  About: { eyebrow: "About", title: "Designed for clarity over complexity.", body: "SOPRANOVA makes data, analysis and action legible to the teams responsible for consequential decisions." },
  Contact: { eyebrow: "Contact", title: "Let’s discuss your intelligence layer.", body: "Use the secure access flow to explore the application. Sales and service integrations can be configured in a future release." },
};

export function MarketingPage({ section }: { section?: string }) {
  const copy = section ? sectionCopy[section] : { eyebrow: "Enterprise Intelligence", title: "Make decisions with the whole enterprise in view.", body: "SOPRANOVA brings governed data, AI agents, persistent intelligence and workflow execution into an elegant operating layer." };
  return <div className="min-h-screen bg-[#FAFAF8] text-[#1A1F3C]"><header className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5"><Link href="/" className="font-semibold tracking-[0.18em]">SOPRANOVA</Link><nav className="hidden items-center gap-6 text-sm text-[#6B6660] md:flex"><Link href="/platform">Platform</Link><Link href="/intelligence">Intelligence</Link><Link href="/agents">Agents</Link><Link href="/enterprise">Enterprise</Link></nav><button onClick={startLogin} className="rounded-xl bg-[#1A1F3C] px-4 py-2 text-sm font-medium text-[#F8F6F2]">Sign in</button></header><main className="mx-auto max-w-7xl px-5 py-20 md:py-28"><div className="grid gap-12 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><section><p className="sn-label text-[#6B7FBF]">{copy.eyebrow}</p><h1 className="mt-5 max-w-3xl font-serif text-5xl leading-[1.04] tracking-tight md:text-7xl">{copy.title}</h1><p className="mt-6 max-w-xl text-lg leading-relaxed text-[#6B6660]">{copy.body}</p><div className="mt-8 flex flex-wrap gap-3"><button onClick={startLogin} className="inline-flex items-center gap-2 rounded-xl bg-[#1A1F3C] px-5 py-3 text-sm font-medium text-[#F8F6F2]">Access workspace <ArrowRight size={16} /></button><Link href="/platform" className="rounded-xl border border-[#E8E6E2] px-5 py-3 text-sm font-medium text-[#1A1F3C]">Explore platform</Link></div></section><section className="relative overflow-hidden rounded-[2rem] border border-[#E8E6E2] bg-[#F4F3F0] p-8 shadow-[0_24px_80px_rgba(26,31,60,.08)]"><div className="absolute -right-24 -top-24 h-56 w-56 rounded-full bg-[#6B7FBF]/15 blur-3xl" /><div className="relative space-y-4"><div className="rounded-2xl bg-[#1A1F3C] p-5 text-[#F8F6F2]"><Sparkles size={18} className="mb-7 text-[#BFC9F4]" /><p className="text-xs uppercase tracking-[.18em] text-[#BFC9F4]">Intelligence</p><p className="mt-2 text-lg leading-snug">Explainable enterprise reasoning, bound to a secure workspace.</p></div><div className="grid grid-cols-2 gap-4"><Feature icon={BrainCircuit} label="AI Agents" text="Tracked execution" /><Feature icon={ShieldCheck} label="Governance" text="Workspace RBAC" /></div></div></section></div></main></div>;
}

export function AccessPage() {
  const [location, setLocation] = useLocation();
  const [mode, setMode] = useState<"login" | "register">(location === "/signup" ? "register" : "login");
  const utils = trpc.useUtils();
  const login = trpc.auth.login.useMutation({ onSuccess: user => { utils.auth.me.setData(undefined, user); setLocation("/app/dashboard"); } });
  const register = trpc.auth.register.useMutation({ onSuccess: user => { utils.auth.me.setData(undefined, user); setLocation("/app/dashboard"); } });
  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    const email = String(data.get("email") ?? "");
    const password = String(data.get("password") ?? "");
    if (mode === "register") register.mutate({ name: String(data.get("name") ?? ""), email, password });
    else login.mutate({ email, password });
  };
  const error = login.error ?? register.error;
  const pending = login.isPending || register.isPending;
  return <div className="grid min-h-screen bg-[#FAFAF8] lg:grid-cols-2"><section className="relative hidden overflow-hidden bg-[#1A1F3C] p-14 text-[#F8F6F2] lg:flex lg:flex-col lg:justify-between"><Link href="/" className="relative font-semibold tracking-[0.18em]">SOPRANOVA</Link><div className="relative max-w-md"><p className="font-serif text-4xl leading-tight">The intelligence layer your enterprise has been missing.</p><p className="mt-5 text-sm leading-relaxed text-[#D8D6ED]">A secure workspace, built around scoped access and operational clarity.</p></div><div className="absolute inset-0 bg-[radial-gradient(ellipse_at_30%_65%,rgba(107,127,191,.25),transparent_60%)]" /></section><section className="grid place-items-center p-6"><form onSubmit={submit} className="w-full max-w-sm"><Link href="/" className="text-sm font-semibold tracking-[0.18em] lg:hidden">SOPRANOVA</Link><p className="sn-label mt-14 text-[#6B7FBF]">Secure access</p><h1 className="mt-3 text-3xl font-medium">{mode === "login" ? "Welcome back" : "Create your workspace"}</h1><p className="mt-3 text-sm leading-relaxed text-[#8C887F]">{mode === "login" ? "Sign in with your SOPRANOVA credentials." : "Create an independent SOPRANOVA account and initial workspace."}</p>{mode === "register" && <label className="sn-label mt-6 block">Full name<input required name="name" autoComplete="name" className="mt-2 w-full rounded-xl bg-[#F4F3F0] px-3 py-3 text-sm font-normal outline-none ring-1 ring-transparent focus:ring-[#6B7FBF]" /></label>}<label className="sn-label mt-4 block">Email<input required type="email" name="email" autoComplete="email" className="mt-2 w-full rounded-xl bg-[#F4F3F0] px-3 py-3 text-sm font-normal outline-none ring-1 ring-transparent focus:ring-[#6B7FBF]" /></label><label className="sn-label mt-4 block">Password<input required type="password" name="password" minLength={12} autoComplete={mode === "login" ? "current-password" : "new-password"} className="mt-2 w-full rounded-xl bg-[#F4F3F0] px-3 py-3 text-sm font-normal outline-none ring-1 ring-transparent focus:ring-[#6B7FBF]" /></label>{mode === "register" && <p className="mt-2 text-xs text-[#8C887F]">Use at least 12 characters. Passwords are stored only as secure hashes.</p>}<button disabled={pending} className="mt-7 flex w-full items-center justify-center gap-2 rounded-xl bg-[#1A1F3C] py-3 text-sm font-medium text-[#F8F6F2] disabled:bg-[#D4D1CB]">{pending ? "Please wait…" : mode === "login" ? "Sign in" : "Create account"}<ArrowRight size={16} /></button>{error && <p className="mt-3 rounded-xl bg-[#FDF0EE] p-3 text-sm text-[#B8675A]">{error.message}</p>}<button type="button" onClick={() => setMode(current => current === "login" ? "register" : "login")} className="mt-5 w-full text-center text-sm font-medium text-[#6B7FBF]">{mode === "login" ? "Need an account? Create one" : "Already have an account? Sign in"}</button></form></section></div>;
}

function Feature({ icon: Icon, label, text }: { icon: typeof BrainCircuit; label: string; text: string }) { return <div className="rounded-2xl border border-[#E8E6E2] bg-[#FAFAF8] p-4"><Icon size={17} className="text-[#6B7FBF]" /><p className="mt-5 text-sm font-medium">{label}</p><p className="mt-1 text-xs text-[#8C887F]">{text}</p></div>; }
