import { Activity, ArrowUpRight, Bot, Database, FileSearch, GitBranch, Headphones, LockKeyhole, Workflow } from "lucide-react";
import { Link } from "react-router";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";

export const landingWorkflow = [
  { label: "Knowledge", detail: "Connect sources, documents, and memory.", icon: FileSearch },
  { label: "AI Agent", detail: "Give a clear role and operating boundary.", icon: Bot },
  { label: "Reasoning", detail: "Ask across governed workspace context.", icon: GitBranch },
  { label: "Tools", detail: "Use procedures, actions, and channels.", icon: Workflow },
  { label: "Decision", detail: "Keep evidence close to the next move.", icon: Activity },
];

const capabilityBlocks = [
  { eyebrow: "Agent builder", title: "Build with the context in view.", detail: "Configure purpose, knowledge, procedures, actions, and deployment state without losing the operating story.", href: "/agents", icon: Bot },
  { eyebrow: "Evidence layer", title: "Understand every conversation.", detail: "Persisted conversations can retain source references and expose a Trace/Sources view in the protected experience.", href: "/intelligence", icon: FileSearch },
  { eyebrow: "Control layer", title: "Move from insight to action.", detail: "Channels, human handoff, procedures, and actions stay scoped to the workspace that owns them.", href: "/platform", icon: Headphones },
];

export const landingConnectors = [
  { label: "HTTP sources", detail: "Connected external context", icon: Database },
  { label: "Documents", detail: "Validated workspace files", icon: FileSearch },
  { label: "Memory", detail: "Persistent enterprise context", icon: LockKeyhole },
  { label: "Channels", detail: "Web, help, email, API", icon: Headphones },
  { label: "Actions", detail: "Controlled operational calls", icon: Workflow },
  { label: "Audit trail", detail: "Reviewable activity", icon: Activity },
];

export function LandingSections() {
  return <>
    <section className="border-y border-[#E8E8E6] bg-[#F8F8F7]">
      <div className="mx-auto max-w-7xl px-6 py-24 lg:px-10">
        <div className="mx-auto max-w-2xl text-center"><p className="sn-label mb-4 text-[#6B7FBF]">From knowledge to action</p><h2 className="sn-display text-4xl leading-tight text-[#111111] md:text-5xl">One clear path through the system.</h2><p className="mx-auto mt-5 max-w-xl text-base leading-relaxed text-[#6B6B6B]">A clean operating loop makes complex enterprise work easier to inspect, explain, and move forward.</p></div>
        <div className="mt-14 grid gap-px overflow-hidden rounded-2xl border border-[#E8E8E6] bg-[#E8E8E6] md:grid-cols-5">{landingWorkflow.map((item, index) => { const Icon = item.icon; return <div key={item.label} className="relative bg-white p-6"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#F3F3F1] text-[#6B7FBF]"><Icon size={16} /></span><p className="mt-8 text-sm font-semibold text-[#111111]">{item.label}</p><p className="mt-2 text-xs leading-relaxed text-[#6B6B6B]">{item.detail}</p>{index < landingWorkflow.length - 1 && <span className="absolute right-[-9px] top-10 z-10 hidden h-px w-[18px] bg-[#B8B8B2] md:block" />}</div>; })}</div>
      </div>
    </section>

    <section className="mx-auto max-w-7xl px-6 py-24 lg:px-10">
      <div className="grid gap-14 lg:grid-cols-[.75fr_1.25fr] lg:items-start"><div><p className="sn-label mb-4 text-[#6B7FBF]">Product surface</p><h2 className="sn-display max-w-md text-4xl leading-tight text-[#111111] md:text-5xl">See the operating layer, not just the answer.</h2><p className="mt-5 max-w-md text-base leading-relaxed text-[#6B6B6B]">The public experience introduces the system. The protected workspace carries the real data, actions, evidence, and controls.</p><Link to="/platform" className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-[#5B6FA8] hover:text-[#111111]">Explore the platform <ArrowUpRight size={15} /></Link></div><div className="grid gap-3 md:grid-cols-3">{capabilityBlocks.map((item) => { const Icon = item.icon; return <Link key={item.title} to={item.href} className="group border border-[#E8E8E6] bg-white p-6 transition duration-200 hover:-translate-y-1 hover:border-[#C9C9C2] hover:shadow-[0_10px_30px_rgba(0,0,0,.06)]"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#F3F3F1] text-[#6B7FBF]"><Icon size={16} /></span><p className="mt-8 text-[11px] font-semibold uppercase tracking-[.14em] text-[#999999]">{item.eyebrow}</p><h3 className="mt-3 text-xl font-semibold tracking-[-.02em] text-[#111111]">{item.title}</h3><p className="mt-3 text-sm leading-relaxed text-[#6B6B6B]">{item.detail}</p><span className="mt-6 inline-flex items-center gap-1 text-xs font-semibold text-[#5B6FA8]">Open surface <ArrowUpRight size={13} className="transition group-hover:translate-x-1 group-hover:-translate-y-1" /></span></Link>; })}</div></div>
    </section>

    <section className="bg-[#F8F8F7]">
      <div className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><div className="grid gap-14 lg:grid-cols-[1fr_1fr] lg:items-center"><div><p className="sn-label mb-4 text-[#6B7FBF]">Analytics with context</p><h2 className="sn-display max-w-lg text-4xl leading-tight text-[#111111] md:text-5xl">Understand what changed, then decide what matters.</h2><p className="mt-5 max-w-lg text-base leading-relaxed text-[#6B6B6B]">Workspace analytics are designed to make signals inspectable. No decorative metrics are shown here until a connected workspace supplies the underlying records.</p><div className="mt-8 space-y-3">{["Conversation activity", "Agent performance", "Decision and audit trail"].map((label) => <div key={label} className="flex items-center gap-3 border-b border-[#E8E8E6] py-3 text-sm text-[#333333]"><span className="h-2 w-2 rounded-full bg-[#6B7FBF]" />{label}<span className="mr-0 ml-auto text-xs text-[#999999]">Workspace-scoped</span></div>)}</div></div><div className="border border-[#E8E8E6] bg-white p-6 shadow-[0_10px_30px_rgba(0,0,0,.04)]"><div className="flex items-center justify-between border-b border-[#E8E8E6] pb-4"><span className="sn-label">Signal view</span><span className="text-xs text-[#999999]">Live when connected</span></div><div className="mt-8 h-48 rounded-xl bg-[#F3F3F1] p-5"><div className="flex h-full items-end gap-2">{[28, 46, 38, 64, 52, 76, 68, 86, 72, 92].map((height, index) => <span key={index} className="min-w-0 flex-1 rounded-t-sm bg-[#A9B8FF]" style={{ height: `${height}%`, opacity: 0.35 + index * 0.055 }} />)}</div></div><p className="mt-5 text-sm leading-relaxed text-[#6B6B6B]">A visual shell for real workspace signals. The production dashboard remains the source of truth.</p></div></div></div>
    </section>

    <section className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="sn-label mb-4 text-[#6B7FBF]">Works with your operating stack</p><h2 className="sn-display max-w-md text-4xl leading-tight text-[#111111] md:text-5xl">Connect the surfaces your team already uses.</h2><p className="mt-5 max-w-md text-base leading-relaxed text-[#6B6B6B]">SOPRANOVA exposes the connector categories already supported by the product, without implying a provider integration that has not been configured.</p></div><div className="grid gap-px overflow-hidden rounded-2xl border border-[#E8E8E6] bg-[#E8E8E6] sm:grid-cols-2 lg:grid-cols-3">{landingConnectors.map((item) => { const Icon = item.icon; return <div key={item.label} className="bg-white p-5"><Icon size={18} className="text-[#6B7FBF]" /><p className="mt-6 text-sm font-semibold text-[#111111]">{item.label}</p><p className="mt-1 text-xs text-[#999999]">{item.detail}</p></div>; })}</div></div></section>

    <section className="bg-[#111111] text-white"><div className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><p className="sn-label text-[#A9B8FF]">Enterprise foundations</p><h2 className="sn-display mt-4 max-w-md text-4xl leading-tight md:text-5xl">Serious about the path from data to decision.</h2><p className="mt-5 max-w-md text-base leading-relaxed text-white/60">Workspace boundaries, role-aware access, encrypted credentials, audit events, and explicit provider states keep the operating layer reviewable.</p></div><div className="grid gap-3 sm:grid-cols-2">{[{ label: "Workspace isolation", icon: LockKeyhole }, { label: "Role-aware access", icon: Headphones }, { label: "Audit events", icon: Activity }, { label: "Controlled actions", icon: Workflow }].map((item) => { const Icon = item.icon; return <div key={item.label} className="border border-white/10 p-5"><Icon size={18} className="text-[#A9B8FF]" /><p className="mt-8 text-sm font-medium">{item.label}</p><p className="mt-2 text-xs leading-relaxed text-white/45">Available as a product capability; compliance certifications are not claimed here.</p></div>; })}</div></div></div></section>

    <section id="pricing" className="bg-[#F8F8F7]"><div className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><div className="mx-auto max-w-2xl text-center"><p className="sn-label mb-4 text-[#6B7FBF]">A plan for the operating layer you need</p><h2 className="sn-display text-4xl leading-tight text-[#111111] md:text-5xl">Start with the surface that fits your team.</h2><p className="mx-auto mt-5 max-w-xl text-base leading-relaxed text-[#6B6B6B]">SOPRANOVA pricing is configured around workspace scope, connected context, and operating requirements. No placeholder prices are shown.</p></div><div className="mt-12 grid gap-3 md:grid-cols-3">{[{ name: "Starter", detail: "Explore the core operating loop", cta: "Create an account" }, { name: "Business", detail: "Connect data, agents, and actions", cta: "Talk to an expert" }, { name: "Enterprise", detail: "Shape a governed operating layer", cta: "Talk to an expert" }].map((plan, index) => <div key={plan.name} className={`border bg-white p-7 ${index === 1 ? "border-[#6B7FBF] shadow-[0_10px_30px_rgba(0,0,0,.06)]" : "border-[#E8E8E6]"}`}><p className="text-lg font-semibold text-[#111111]">{plan.name}</p><p className="mt-3 min-h-10 text-sm leading-relaxed text-[#6B6B6B]">{plan.detail}</p><p className="mt-8 text-xs font-medium uppercase tracking-[.12em] text-[#999999]">Custom scope</p><Link to={index === 0 ? "/signup" : "/contact"} className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-[#5B6FA8]">{plan.cta} <ArrowUpRight size={14} /></Link></div>)}</div></div></section>\n\n    <section className="mx-auto max-w-3xl px-6 py-24 lg:px-10"><div className="text-center"><p className="sn-label mb-4 text-[#6B7FBF]">Questions, answered clearly</p><h2 className="sn-display text-4xl leading-tight text-[#111111] md:text-5xl">A simpler way to understand the platform.</h2></div><Accordion type="single" collapsible className="mt-10">{[
      ["What is SOPRANOVA?", "SOPRANOVA connects governed enterprise context, AI reasoning, agents, decisions, and operational actions in one workspace."],
      ["Where does the product data live?", "The protected product experience reads workspace-scoped records through the existing server contracts. Public sections do not imply access to customer data."],
      ["Can I inspect the evidence behind an answer?", "When a persisted intelligence response includes sources, the protected Intelligence view exposes Trace and Sources inspection."],
      ["Are all integrations already active?", "No. Supported connector categories are shown honestly, while provider-specific connections remain scoped until configured."],
    ].map(([question, answer], index) => <AccordionItem key={question} value={`faq-${index}`}><AccordionTrigger className="text-left text-base font-medium text-[#111111]">{question}</AccordionTrigger><AccordionContent className="text-sm leading-relaxed text-[#6B6B6B]">{answer}</AccordionContent></AccordionItem>)}</Accordion></section>
  </>;
}
